### ISSUE TITLE
Expose API around non-user "hidden" branches

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-link#103]
To be able to display the tracking graph of projects to users, we need a way to interpret the branch information provided by `link` and `surf`. For eg. `/rad/remotes/bob/remotes/alice/master` would be mapped to `{user: "alice", branch: "master"}`, and `/src/*` would be mapped to the user's working copy.

The simpliest way this could work is that `radicle-link` provides a `parse` function for branch names, that returns structured data.

To do this, we don't want to be hiding any branch names from surf, and so #30 should be closed.

**Comment by cloudhead** [comment]
@kim @FintanH let me know if this approach makes sense. Another approach would be for `link` to provide that data directly, not going through surf, and then we implement #30.

**Comment by FintanH** [comment]
This makes sense to me at least. Having structured data means we can provide type-safe queries, e.g. you can't give `surf` a `rad` branch. 

> Another approach would be for link to provide that data directly

Can you elaborate here, I'm not sure I understand :)

**Comment by cloudhead** [comment]
> This makes sense to me at least. Having structured data means we can provide type-safe queries, e.g. you can't give surf a rad branch.

I mean, you *can*, because surf wouldn't distinguish between the different "types" of branch, unless we made a change to surf. Or am I missing something?

> Can you elaborate here, I'm not sure I understand :)

Well, since radicle-link must have some concept of the remotes (and the tracking graph), for it to be able to create these branch paths, perhaps we can obtain that information directly from there, without going through the branch names and `surf`.

**Comment by kim** [comment]
I realise that there are two small, but annoying complications. 

Consider a tracking relation like this:

        alice -> bob -> alice

What we'd want here is to return only _one_ `alice`, ideally with the more recent state (for some definition of). Also, `alice` and `bob` are actually `rhubarbyuiopzxc` and `qwerthgfddaaxc`, so we also need to read the metadata to get at the nicknames.

I'd need to give it more thought, but I think it boils down to:

* `surf::Browser` only being able to access `refs/heads` (ie. `BranchType::Local`). Handling "special" branches is up to the application, and I think we'll need to experiment a bit to find out how exactly.
* Another method which returns something like, or an iterator thereof:

```rust
struct Remote {
    id: PeerId,
    meta: meta::Contributor, // subject to change!
    branches: Set<Branch>, // not including nested remotes
    tracks: Set<PeerId>,
}

struct Branch {
    name: String, // branch name without any prefix
    branch: surf::BranchName, // actual branch name
}
```
* Potentially yet another method which yields only an adjacency list or something of the tracking graph `PeerId`s without incurring the IO for reading metadata and stuff.

**Comment by FintanH** [comment]
> Well, since radicle-link must have some concept of the remotes (and the tracking graph), for it to be able to create these branch paths, perhaps we can obtain that information directly from there, without going through the branch names and surf.

Ah, it slipped my mind that you're getting the branches through `surf` :facepalm: 

> `surf::Browser` only being able to access `refs/heads` (ie. `BranchType::Local`). Handling "special" branches is up to the application, and I think we'll need to experiment a bit to find out how exactly.

If we go down this route I wonder how you would list the branches of your peers and also browse their code? Like what if I wanted to see Alice's work on `alice/update-surf-branch-logic`? This also makes `surf` a less general API, but not sure if it's a bad thing in this case, I'd have to think about it more.

**Comment by kim** [comment]
> If we go down this route I wonder how you would list the branches of your peers and also browse their code?

That’s the `Branch` type above, which is missing visibility annotations: `name` would be public, while `branch` would be private — thus allowing to map it to any branch naming convention, and be able to change that convention later.

**Comment by FintanH** [comment]
Right, one thing to note though is that `upstream` would be getting the branches through the link API rather than the `surf`. Could that be confusing from an API perspective?

**Comment by cloudhead** [comment]
Hmm in terms of the circular tracking, I don't see a problem so far, at least when looking at it from just the "what repositories to show" perspective. You're right though that given a duplicate, we may want to select the one with the longest history..

Alice's POV:
`remotes/bob`
`remotes/bob/remotes/alice`

Result: [`bob`], since `alice` is "self", and we don't allow duplicates.

Bob'x POV:
`remotes/alice`
`remotes/alice/remotes/bob`

Result: [`alice`]

**Comment by kim** [comment]
It’s that it should also not be surfaced how tracking branches are implemented — the hierarchical naming convention is a working hypothesis, as we can discover it remotely using git alone. Otoh, we have only `PATH_MAX` characters, and this remote discovery may not be needed. Iow, we’d like to be able to change the implementation without breaking the API.

**Comment by cloudhead** [comment]
Ah gotcha, yeah in that case I think this should be exposed fully through `radicle-link`. This gives us the flexibility later to encode the information wherever we want.

**Comment by FintanH** [comment]
I believe this isn't as relevant anymore. Currently, we have the `namespace` RFC which provides us with the ability to ask the `remote` for their `rad/self`, giving us access to a handle + their `PeerId`. I'm going to close this and the follow-up is in the repository selector work.
