### ISSUE TITLE
Avoid Boolean Blindness

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#107]
I think code that matches on an enum and returns a `bool`, such as https://github.com/radicle-dev/radicle-link/blob/master/librad/src/id/entity.rs#L128-L171, will lead to boolean blindness. It would be my preference to have the caller just match on the variant.

I think in the case where the variant holds data and the caller would wish to zoom in on that data, such as here https://github.com/radicle-dev/radicle-link/blob/master/librad/src/id/entity.rs#L123-L124,  we could provide functions that return `Option` with the data inside.

Creating this ticket to have a discussion about these kinds of practices in the codebase.

**Comment by kim** [comment]
I'm not sure what you mean by boolean blindness in this specific case. That the caller would essentially create a non-exhaustive pattern match if they'd instead had the idea to create a giant `if {} else if {} else if {}`?

I agree that it is potentially a bit too fine-grained, but I can also see the utility of simple good/bad/unknown predicates, in the same spirit as `is_ok()`/`is_err()`.

**Comment by FintanH** [comment]
Ya, essentially there's no need to have functions that match a particular case and return a boolean for it. That's what `match` is for.

> I agree that it is potentially a bit too fine-grained, but I can also see the utility of simple good/bad/unknown predicates, in the same spirit as is_ok()/is_err().

I imagine that `is_ok` and `is_err` are pretty much there for filtering cases.

I guess the point is that we should think about what functionality we want to add and why it would be useful. Maybe there's a use for the boolean checks but I would like to see why. Less code, fewer problems :sunglasses:

**Comment by kim** [comment]
We have gotten our booleans backwards so many times that we [introduced our own](https://github.com/radicle-dev/radicle-link/blob/a8f79e4b557030c07e64f7cfb299c000c754c751/librad/src/git/types.rs#L43-L48)
