### ISSUE TITLE
Entities: Empty String Checks

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#109]
I noticed that all we do is verify that `name` isn't `None`, but we don't check whether a field like `name` isn't the empty string. See here: https://github.com/radicle-dev/radicle-link/blob/master/librad/src/id/entity.rs#L267-L269.

Should we check for empty strings?

**Comment by kim** [comment]
Yes, and we should solve this problem once and for all, for all datatypes which can be empty (or not) (see also #16)

**Comment by FintanH** [comment]
I'm fine with non-correct-by-construction data if you have to jump through too many hoops to make the API usable. So smart constructors are fine by me.

It's just that in the case of `NonEmpty` vectors, the win is clear when maintaining the head of the list and the operations, such as `head`, `split_first`, or `split` are _definitely_ safe due to the construction rather than trusting the implementor :)

**Comment by kim** [comment]
Closed via 1a7c3f48dc156c14166764b2e3f862b867cc2812 in `next`
