### ISSUE TITLE
EntityData: typed setters

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#115]
`EntityData` is supposed to be a "dumb" data container, where validation occurs only when converting to an `Entity`, which is immutable. That is fine, but the implementation turns out to yield a quite impractical API: all fields are of type `String`, while the library user will have appropriately typed values at hand. That is, a serialisation roundtrip is unnecessarily enforced.

Instead, `EntityData` should be strongly typed. `Entity` can then just consume `EntityData`, effectively making it immutable.

Note that this will require appropriately defined `serde` impls for `Hash` and `PublicKey` in the context of JSON.

**Comment by FintanH** [comment]
So I presume this is regarding thing like the [`hash`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/entity/data.rs#L63-L64) family of fields and [`EntitySignatureData`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/entity/data.rs#L71)?

But are you also advocating we provide types for [`revision`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/entity/data.rs#L62) and what not? If so, I feel like we're moving towards validation functions and then compute the hash of the result of them.

**Comment by kim** [comment]
We have:

```rust
pub struct Entity<T> {
    status: VerificationStatus,
    name: String,
    revision: u64,
    rad_version: u8,
    hash: Hash,
    root_hash: Hash,
    parent_hash: Option<Hash>,
    signatures: HashMap<PublicKey, EntitySignature>,
    keys: HashSet<PublicKey>,
    certifiers: HashSet<RadUrn>,
    info: T,
}

pub struct EntityData<T> {
    pub rad_version: u8,
    pub name: Option<String>,
    pub revision: Option<u64>,
    pub hash: Option<String>,
    pub root_hash: Option<String>,
    pub parent_hash: Option<String>,
    pub signatures: Option<HashMap<String, EntitySignatureData>>,
    pub keys: HashSet<String>,
    pub certifiers: HashSet<String>,
    pub info: T,
}
```

Where `Entity::to_builder` gives you `EntityData`. I totally agree with the pattern that there is a mutable type, which gets "frozen" and "thawed" through an immutable one. What I don't find practical is that we loose (almost) all type information along the way.

My proposal is something like:

```rust
#[derive(Serialize, Deserialize)]
pub struct Entity<T> {
    name: String,
    revision: u64,
    rad_version: u8,
    hash: Hash,
    root_hash: Hash,
    parent_hash: Option<Hash>,
    signatures: HashMap<PublicKey, EntitySignature>,
    keys: HashSet<PublicKey>,
    certifiers: HashSet<RadUrn>,
    info: T,
}

impl<T> Entity<T> {
    /// Update the payload, clearing / recomputing envelope data as applicable
    pub fn modify(&mut self, update: FnOnce(T) -> T) -> Self

    /// Check the invariants and either return `Self` wrapped in a success variant, or an error
    pub async fn compute_status(&self, resolver: &impl Resolver<User) -> Result<OkStatus, MehStatus>

    // etc.
}
```
