### ISSUE TITLE
Type witnesses for entity verification status

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#121]
It should be possible to assert on the type level that an `Entity` value has the desired (success) `VerificationStatus`. For example, initialising a repo from an entity should take a type which witnesses that it does not have a parent (ie. is at revision 1) and is signed by the local key, instead of checking these invariants at runtime.

As one does not simply do type witnesses in Rust, this will probably be newtype wrappers, either returned from the corresponding verification methods, or with "smart" constructors enforcing exactly the preconditions we're after.

**Comment by massimiliano-mantione** [comment]
Fixed by #147 (which includes #148).
