### ISSUE TITLE
Implement entity update

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#122]
Note that this will require a validation function with does _not_ take the quorum rules into account -- the user might be unilaterally proposing an update. Instead, after fetching, we will check if the receiving end is a member of the certifiers set, and if not reset the updated (non-quorum-passing) `rad/id` branch to the previous version. This needs to be a separate from the actual fetch, and invoked from the library user, as its return type must indicate if there is any action needed from the receiving side.

An alternative "protocol" would be to exchange update proposals on a separate branch (say `rad/id-proposals`, or user-specified), and only allow `rad/id` updates given a fully validated entity update.

**Comment by kim** [comment]
Current thinking in #127 suggests the alternative protocol: it simplifies things if every `rad/id` found in a repo is supposed to be valid, and they may only differ by recency. So, exchanging proposals would similar to exchanging patches -- but we'll need to define some convention for that.

**Comment by xla** [comment]
Is this still relevant?

**Comment by kim** [comment]
We can consider it implemented as per #310, pending integration
