### ISSUE TITLE
Implement reading the entity metadata from a repo

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#123]
Should include:

* A method to get the head of `rad/id` (the state acc. to the local peer)
* A method to get the head of any `refs/remotes/{}/rad/id`, given a `PeerId`
* Optional: get the heads of all `rad/id` branches owned by the current set of certifiers
* A method to walk the history of either the local, or any other `rad/id` branch, yielding `Entity<T>` (not `Commit`).

**Comment by FintanH** [comment]
I feel like the majority of this is done @kim. Just not the walking of the history. Should we close this and just have one ticket for that?

**Comment by kim** [comment]
> Should we close this and just have one ticket for that?

:+1:

**Comment by FintanH** [comment]
Done https://github.com/radicle-dev/radicle-link/issues/222
