### ISSUE TITLE
Checkout a working copy

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#138]
As outlined in #127, there will need to exist a library function which takes an identity hash + a directory path, and checks out a working copy of the repo to that path, setting up a remote so `push`, `pull`, and `branch -a` works.

Things to consider:

* The target directory may already be a git repo
* The nicknames corresponding to `PEER_ID` remotes will need to be resolved (#124)
    * Note that several `PEER_ID`s may map to the same user identity
* The `HEAD` should be chosen acc. to the project "consensus" -- we will, however, only consider single machine / maintainer

**Comment by cloudhead** [comment]
I'm looking into this. How should the working copy be created? `git clone` would clone the entire repository unless we fiddle with `--filter` somehow.. Or should we use something like `git worktree`?

**Comment by kim** [comment]
Since #233 we have a remote helper which will only consider the namespace corresponding to the URN. We still need a way to determine the HEAD (#234), and to create a `.git/config` for the working copy which adds remotes of interest as actual remotes (#235).

**Comment by kim** [comment]
Superseded by #234, #235

**Comment by cloudhead** [comment]
Ah makes sense, thanks.
