### ISSUE TITLE
User::create should be User::new

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#156]
Found that `User` has a function called `create`: https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/user.rs#L162.
This should really be `new` to follow the iiiiiidioms. Just wanna track it here because it threw me through a loop briefly.

**Comment by massimiliano-mantione** [comment]
Our beloved clippy was complaining that `new` should return `Self`, but here the Ok branch of the result cannot be `Self` (because `User<Draft>` is not the same type as `User<ST>`).
So I renamed `new` to `create`...
I should probably have left a comment about it.

**Comment by FintanH** [comment]
Ah! That makes sense :) I'll close this :ok_hand:
