### ISSUE TITLE
Paths in PeerApi

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#157]
@kim while spelunking through the API, I was trying to see if there was a way to retrieve the `Paths` that was used to construct the `Peer`/`PeerApi`. I can't seem to find one. So I'm thinking it should be in the `PeerApi` struct with a getter. Do you see any reason why that wouldn't be the case?

**Comment by kim** [comment]
No, go crazy.

The only thing that needs some review is if we could avoid keeping the
secret key in memory. Ideally, it should be encrypted and supplied only
where needed.

**Comment by FintanH** [comment]
Cool cool :ok_hand: re: secret key that makes sense.

These tickets are grocery list of things I'm running into while integrating so feel free to just thumbs up or whatever if they make sense :)
