### ISSUE TITLE
Bootstrap: Open or Init or Both?

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#160]
Is it ok to assume that we have an existing git repo during bootstrapping: https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L245? Or should it be more like `open_or_init`? :thinking:

**Comment by FintanH** [comment]
Ah I see we `init` in the setup https://github.com/radicle-dev/radicle-link/blob/master/librad/tests/testnet.rs#L75

**Comment by kim** [comment]
Yes it should potentially init itself if it doesn’t already exist
