### ISSUE TITLE
User::create can come with signing

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#161]
It seems like [User::create](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/user.rs#L162) could come signed with its own `SecretKey`. This would make it easier to bootstrap a user without needing a resolver.

**Comment by massimiliano-mantione** [comment]
I have been thinking a lot about this, and I think I have a better solution.

The problematic step is the `check_key` function, and the fact that it needs the resolver to (potentially) check that the signatory actually owns the key.

Currently `check_key` is a problem also for another reason (it does not take into account key revocations), but let's keep this for later :-)

We could acknowledge that there are two ways to sign an entity: either with a key owned by the entity itself, or with a key owned by an arbitrary user (they are represented by the two variants of the `Signatory` type).

In each case there's no need for a resolver, or even for a generic `check_key` invocation: in the "owned" case the key must be owned by the entity and in the "user" key it must be owned by the signatory user.
I'll provide a PR with the two simplified methods.
