### ISSUE TITLE
Send/Sync Peer

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#165]
I'm creating this ticket to discuss a compatibility concern with `radicle-upstream`.

The main entry point to `librad` is through `PeerApi`, and `PeerApi` implements `Send` but not `Sync`. This is due to a git `Repository` being safe to send to other threads. The underlying `Repository`, however, can easily be mutated using a `&Repository` which is no bueno for `Sync`.

The crux is that `proxy` uses [`RwLock`](https://docs.rs/tokio/0.2.21/tokio/sync/struct.RwLock.html) to share data between its `warp` threads. This requires things to be `Send + Sync` if we want to grab a [`RwLockReadGuard`](https://docs.rs/tokio/0.2.21/tokio/sync/struct.RwLockReadGuard.html) or a [`RwLockWriteGuard`](https://docs.rs/tokio/0.2.21/tokio/sync/struct.RwLockWriteGuard.html).

So I wanted to create the space for discussing how this can be resolved for future integration. For the time being, I have stuck in the un-utterable: `unsafe impl Sync for UserPeer {}` :scream_cat: 

cc @xla @kim @massimiliano-mantione

**Comment by kim** [comment]
What’s the problem with Arc<Mutex<PeerApi>>?

**Comment by FintanH** [comment]
Nothing... :facepalm: Sorry, this was my naivety around Send/Sync/async/await

**Comment by kim** [comment]
Note that the PeerApi is very low-level currently - it is likely that we
won’t hand out the Storage and Protocol directly in the future, but expose
higher-level operations implemented in terms of those. We can move the
mutex inside PeerApi then, making it Send + Sync

**Comment by FintanH** [comment]
Ya, that makes sense :ok_hand:
