### ISSUE TITLE
Question: Code Repository

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#168]
There's something I'm not quite getting when it comes to how everything links up. So, I'm going to try layout what I understand and maybe there's something I'm missing or maybe it's actually future work.

The question is: What is the relation between a code repository and the monorepo?

When we call [`create_repo`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L139) on a `Project`, it creates a `rad/id` for that project under the particular namespace. What does this mean for an actual project?

For example, say I was to create a project called `git-platinum` that has some Rust and Haskell files in it. How does this get associated with the `Project` I create via `librad`? Should the `Project` say where `git-platinum/.git` lives on the file system? How will the changes in `git-platinum` be communicated via gossip?

Sorry if this has been laid out somewhere already. I think I made unspoken assumptions about how I saw how things worked :)

**Comment by kim** [comment]
[Here](https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/identity_resolution.md#working-copies). Basically, we add a remote to your existing repo, or initialise a fresh one if you don’t have a repo yet.
