### ISSUE TITLE
Implement rustls::ResolvesServerCert

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#195]
In our quest to be able to delegate signing to a vault, agent, or whatever, we need to implement an appropriate `rustls::ResolvesServertCert`.

See also: radicle-dev/radicle-keystore#1

**Comment by kim** [comment]
The description is a bit deceiving: what we need to implement this trait is a way to generate the X509 cert without requiring an actual private key. Existing libraries (we use `rcgen`) don't abstract over this, although the key is only needed to sign the certificate.

The minimalist approach would be to write out the cert in ASN.1 using [`yasna`](https://crates.io/crates/yasna) directly (`rcgen` uses this under the hood, so can serve as a reference). I also found [`picky-asn1-x509`](https://crates.io/crates/picky-asn1-x509), which could be a bit more convenient -- note, however, that we never use an intermediate representation.

**Comment by kim** [comment]
@CodeSandwich In case you have some spare cycles, would you want to take a stab at this?

**Comment by xla** [comment]
Just for clarification, if we solve this issue we can get rid of the `AsPKCS8` constraint in:

https://github.com/radicle-dev/radicle-link/blob/7ec69bd584e59f87a8f99ea4848970386925e6d5/librad/src/net/peer.rs#L123-L128

Is that assumption correct? It's currently blocking the progress of generalized signers downstream in upstream.

**Comment by CodeSandwich** [comment]
@kim Sure, I'll keep it in mind

**Comment by FintanH** [comment]
@xla that's correct afaiu
