### ISSUE TITLE
Upgrade sequoia-pgp and find alternative for sequoia-rfc2822

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#20]
`sequoia-pgp` is moving rather fast and breaking things, better keep up early. `sequoia-rfc2822` seems to be deprecated.

**Comment by nwalfield** [comment]
sequoia-rfc2822 was mostly integrated into sequoia-openpgp.  What were you using it for?

**Comment by kim** [comment]
I needed a type to represent a valid email address — in any context, not
 just PGP. Not sure we’ll need that in the future.

Btw, the `nettle` dependency is causing us some headaches. We likely don’t
need full-blown PGP functionality in the future, but it would be nice to
have just the message types an armor parsing.

**Comment by nwalfield** [comment]
> I needed a type to represent a valid email address — in any context, not just PGP. Not sure we’ll need that in the future.

Ok.

> Btw, the `nettle` dependency is causing us some headaches. We likely don’t need full-blown PGP functionality in the future, but it would be nice to have just the message types an armor parsing.

What troubles are you having with nettle?

Can you explain exactly what functionality you need?  (I'm not sure what you mean by 'message types'.)

Perhaps you could open these as issues on our issue tracker. https://gitlab.com/sequoia-pgp/sequoia/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=

**Comment by kim** [comment]
@nwalfield https://gitlab.com/sequoia-pgp/sequoia/issues/447

Hope this helps!
