### ISSUE TITLE
Use `Signer` trait everywhere

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#216]
Nb. that the trait is `async_trait`, so that might change some signatures

**Comment by massimiliano-mantione** [comment]
Tho questions to understand in better...

On the radicle-link side, would this mean replacing `keys::PublicKey`, `keys::SecretKey`, `keys::Signature` with types from `radicle-keystore`?

And, why is `Signer::sign` async?
All current implementations of it don't use `.await`: which are the future implementations that we know that need to be async?

**Comment by FintanH** [comment]
> On the radicle-link side, would this mean replacing keys::PublicKey, keys::SecretKey, keys::Signature with types from radicle-keystore?

I believe the types would stay the same, but where we sign data that's where we are generic and say it's a `Signer`. Then upstream users would say something like `FileStorage<keys::PublicKey, keys::SecretKey>` 

> And, why is Signer::sign async?

My guess is that some other process will sign the data, e.g. some key credentials client

**Comment by kim** [comment]
> On the radicle-link side, would this mean replacing keys::PublicKey, keys::SecretKey, keys::Signature with types from radicle-keystore?

No. We need our own newtypes due to `impl` coherence. `radicle-keystore`'s contract is that the byte representations are RFC 8032 compliant, and thus can be trivially converted. The goal is to enable delegation of signing to an external process (e.g. an agent), and thus we want to pass around an `impl Signer` instead of a concrete `SecretKey`.

> And, why is Signer::sign async?

Because it may perform IO in order to obtain the signature. `async` code can trivially be made sync using `futures::executor::block_on`, while the other way round requires explicit threading of the reactor runtime (which, sadly, is not standard practice in Rust `async/await`).

**Comment by kim** [comment]
See also #195
