### ISSUE TITLE
Add rad remote config to a working copy

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#219]
When radiclising a repository we need to add the `rad` remote and configure the `fetch/pushspecs`.

**Comment by FintanH** [comment]
Currently, this is done in `radicle-upstream/proxy`. We may want to migrate that code over to `radicle-link` so that if we ever build a CLI, we'll be able to create projects using it, i.e. the logic isn't proxy specific.

**Comment by FintanH** [comment]
This didn't end up being a link concern

**Comment by xla** [comment]
Would it become one if we want to ensure interoperability between different "apps"? As an example build a cli on top of link which wants to create rad ready working copies. This has been a motivation to have librad own the location of include files.

**Comment by FintanH** [comment]
I think it could be the case that the CLI will live in a separate repository. So this issue would probably live there at least.

I think it'd be good to flesh out where this useful git working copy tooling would go anyway :+1:
