### ISSUE TITLE
Ask Network for RadUrn

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#221]
We will want to be able to take a `RadUrn` and ask for the entity that is behind this URN. The steps are the following:

* Announce that we want whatever this `RadUrn` points to
* Attempt to connect to a peer that says they have this `RadUrn`
* Attempt to clone to the monorepo
* Verify the entity - hash, keys, etc.

**Comment by FintanH** [comment]
Not going to create a separate ticket for this, but rather, mention it here. It's a bit unintuitive that way we send out a `RadUrn` into the world without any intent on what should be behind that URN.

Instead we have to ask for it, and see what we have in the goody-bag. Whereas if we had encoded in the URN then it becomes more intuitive that I'm asking for, say, a project and can reject anything that is not a project.

**Comment by cloudhead** [comment]
This is relevant for the seed node "follow" behavior as well, as part of Discovery. Assigning myself from that angle.

**Comment by FintanH** [comment]
Completed
