### ISSUE TITLE
Cannot Certify User

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#225]
At the moment I don't think it's possible to add yourself as the certifier for your `User` while attempting to call `create_repo`. If you tried to do so [this check](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L566) would fail.

Would it be useful to have your URN as a certifier? I would assume so, but I'm not 100% sure.

This would probably be fixed by being able to update entities in the storage and isn't a blocker right now. I just came across it while integrating the `rad/self` work into upstream and I needed to add a certifier to the `Project` being created.

**Comment by kim** [comment]
Not sure what you're trying to do: if you create _your_ user, you can't use another user to sign it, because that other user has to exist already. Instead, "your" users "owns" your local key, ie. `your_user.sign(&your_key, &Signatory::OwnedKey, &resolver)`.

**Comment by FintanH** [comment]
Right, just wanted to make sure that if it did or didn't make sense to add the `RadUrn` of yourself as a `certifier`. Which technically would be possible once we're able to update entities after initially commiting to the monorepo.
