### ISSUE TITLE
Working copy remotes

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#235]
In order to see the remote tracking branches of collaborators via the git CLI
(`git branch -a`), the working copy needs to be configured with actual remote
configs -- the idea being that the fetchspec can be used to map the URN hashes
to something more legible for humans. For example:

```
[remote "cloudhead@hwxyaasdasd]"
    url = rad://hwxyaasdasd
    fetch = +refs/remotes/hwxyaasdasd:refs/remotes/cloudhead@hwxyaasdasd
```

The question here is if we generate this configuration automatically based on
the tracking graph (which can change, and could be huge), generate it only for
the 1st degree tracked peers, or provide a CLI to list remotes is a legible way,
and add them to the local repo config.

**Comment by FintanH** [comment]
@rudolfs and I were wondering if it would make sense if the remotes were set up to point to the monorepo with a fetchspec, i.e.:

```
[remote "cloudhead@hwxyaasdasd]"
    url = file://monorepo.git
    fetch = +refs/namespaces/<id>/refs/remotes/*:refs/remotes/cloudhead@hwxyaasdasd/*
```

Or is there a reason that we use the `rad://` transport for this? Possibly signing?

In general, this back-and-forth collaboration model is a bit fuzzy in our heads. Maybe we could have a chat about how the exchange would work.

**Comment by kim** [comment]
> is there a reason that we use the rad:// transport for this

Yes signing, preventing you from (accidentally) pushing to a remote, preventing you from (accidentially) pushing to the top-level instead of the namespace.

**Comment by FintanH** [comment]
Right, because you wouldn't want to push to a remote. But wouldn't we want to be able to fetch the branches as our `refs/remotes` from the monorepo directly rather than from the rad url?

**Comment by kim** [comment]
Maybe what throws you off here is that `rad://` doesn't have anything to do with the p2p layer -- those URLs (which are never visible to the user) have the scheme `rad-p2p://`. What `rad://` does is to invoke the remote helper, which in turn is just a way to run a `git daemon` (without the socket), namespaced to just the sub-repository you're interested in.

Normally, git remote repositories don't have `refs/remotes`, what git expects is that you map _different_ remote URLs to your _local_ `refs/remotes`. We could get away with a single `[remote]` entry if the `LocalTransport` would rewrite the `refs/remotes` on the monorepo side to include a human-readable prefix. I don't know how to do this without re-implementing `git upload-pack` though.

**Comment by FintanH** [comment]
So, should we actually be setting the remotes to `rad://` even for our own copies? Which is different to what's here: https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/identity_resolution.md#working-copies.

Meaning that the helper will be signing our refs when we push?

I think my confusion is coming from the mixture of the file URL in the identity resolution document and the `rad` URLs here.

**Comment by kim** [comment]
Documentation is when it's always out-of-date, innit? ;)

I thought initially that `url = file://...` would be sufficient, but it wasn't -- not least because `libgit2` doesn't respect the fetchspec at all (except in very sublime cases). So, we have a remote helper now, an **everything** goes through it.

**Comment by FintanH** [comment]
Ach sooooooo... Thanks for the clarification :+1:

**Comment by kim** [comment]
@FintanH Should we close this?

**Comment by rudolfs** [comment]
@kim: now that I've learned a bit about URNs, I'm wondering how "cloudhead@hwxyaasdasd` fits into the grand *scheme* of things?

**Comment by kim** [comment]
@rudolfs It doesn't. What's described here is simply for the purpose of making the output of the `git` CLI decipherable -- instead of something like:

```shell
> git branch -a
mistress
remotes/hxwyaasdasd/heads/mistress
```

you'd get:

```shell
> git branch -a
mistress
remotes/cloudhead@hxwyaasdasd/heads/mistress
```
