### ISSUE TITLE
Template Storage Layout

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#240]
It would be super useful to have a way to generate a fake librad structure for testing. Basically generate the structure that's laid out in the RFC + fill in refs/heads and what not.

It would help testing in librad + any upstream libraries that would like to test against mock data.

**Comment by kim** [comment]
This is not currently possible without creating loopholes (and thus additional equivalence testing effort). To restrict the IO to filesystem operations, `clone_repo` / `fetch_repo` could be parametrised over the `Fetcher`, though (which would need to become a trait).

**Comment by FintanH** [comment]
What if we limit this to `Storage` that doesn't have `WithSigner`? So something like `Storage<()>`. I'd like something to add tests for at least the read-only functions that we can find in `impl<S: Clone> Storage`. Just so I can have more confidence when I'm adding code that gets references :sweat_smile:

**Comment by kim** [comment]
Not sure I understand what you want to achieve. The repository layout
is determined by the clone/fetch operations, so the only way to avoid
actual network IO is to mock the network.

**Comment by FintanH** [comment]
Well I was hoping to get away with just making the storage _look like_ this, without any of the networking:
```
    $PEER_ID/refs/
    `-- namespaces
        `-- $IDENTITY
            `-- refs
                |-- heads # <-- code branches owned by $PEER_ID go here
                |-- rad
                |   |-- id # <-- points to the identity document history
                |   |-- refs
                |   |-- self # <-- points to the identity of $PEER_ID
                |   `-- ids
                |       |-- $CERTIFIER[1]
                |       `-- $CERTIFIER[2]
                `-- remotes
                    `-- $TRACKED_PEER_ID
                        `-- refs
                            |-- heads
                            `-- rad
                                |-- id
                                |-- refs
                                |-- self
                                `-- ids
                                    |-- $CERTIFIER[1]
                                    `-- $CERTIFIER[2]
```

Something like that to mock being able to get the references. Maybe something like `git-platinum`.

**Comment by kim** [comment]
> Maybe something like git-platinum.

I'm not willing to maintain a fixtures-based test harness for this, as this tends to be a lot of work for very little benefit: a fixture can only represent one possible input, which is either a synthetic "happy case", or lot of manual labour to conjure variance in the test inputs. 

The _easiest_ way currently is to eliminate the networking, but not the git IO -- constructing the state must be done through the same code paths. A more fancy approach would be to define all state + transitions as a pure computation which can be interpreted to IO, and implement everything in terms of this. While we know enough by now about the semantics we want to attempts this, I fear that the language we are working with would turn it into a major undertaking.
