### ISSUE TITLE
all_metadata returns remotes

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#250]
While testing remote peers we noticed [`all_metadata`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L234) returns the remote as well. This is surprising since the glob is a single `*` as opposed to `**`.

**Comment by NunoAlexandre** [comment]
I'm hitting a wall here :thinking: 

The `glob` we are passing, `refs/namespaces/*/rad/id`, seems correct. However, it all gets delegated down to `git2`:

``` rust
    /// Create an iterator for the repo's references that match the specified
    /// glob
    pub fn references_glob(&self, glob: &str) -> Result<References<'_>, Error> {
        let mut ret = ptr::null_mut();
        let glob = CString::new(glob)?;
        unsafe {
            try_call!(raw::git_reference_iterator_glob_new(
                &mut ret, self.raw, glob
            ));

            Ok(Binding::from_raw(ret))
        }
    }
```

Now how `glob` is `&str`, not [`glob`](https://docs.rs/glob/0.3.0/glob/), which documents what `*` is meant to cover. From `git2` we don't seem to get such documentation. So this seems to be an issue in `git2` or in a layer beneath. I couldn't find anyone else reporting a similar issue.

Will continue looking. If you have some other insight in the meantime, please ring a bell :)

**Comment by kim** [comment]
This is how `git` and `libgit2` do globbing: 
https://github.com/libgit2/libgit2/blob/c71321a099373753c22055921c8f538afed5ebb6/src/wildmatch.c

Tests as "documentation": 
https://github.com/libgit2/libgit2/blob/c71321a099373753c22055921c8f538afed5ebb6/tests/core/wildmatch.c

I believe the culprit might be this: https://github.com/libgit2/libgit2/blob/c71321a099373753c22055921c8f538afed5ebb6/src/wildmatch.c#L131

The refdb iterator does [not set any flags](https://github.com/libgit2/libgit2/blob/c71321a099373753c22055921c8f538afed5ebb6/src/refdb_fs.c#L620), ie. it's not treating ref names like paths. That is indeed surprising, and should perhaps be raised with `libgit2`.

It is however not crucial that we rely on `libgit2` for this kind of thing -- it will load the entire set of refs into memory anyway, so we can also opt to implement our own globbing. If we do that, it would just be good to not sprinkle it all over the place, as we might eventually want to plug in a custom refdb, so being able to reuse that code one layer down would be neat.

**Comment by NunoAlexandre** [comment]
Superseded by #266
