### ISSUE TITLE
Typesafe Header Send

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#257]
We could probably use the ol' phantom data technique here https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/p2p/transport.rs#L165-L199 to ensure we have sent the header.

Not a major issue, but would be Nice To Have:tm:

**Comment by kim** [comment]
Don't think you can change the type, tho. We could, however, stick the header in an `Option` on construction, and `take` it.

**Comment by kim** [comment]
Since `next`
