### ISSUE TITLE
Git Trailers Utilities

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#267]
We will be using [git trailers](https://git-scm.com/docs/git-interpret-trailers)
for "multisig" commits, and potentially other purposes, too. Unfortunately,
`libgit2` doesn't include any functionality for parsing or otherwise
manipulating trailers in a commit message.

We do not need to replicate exactly what `git-interpret-trailers` does, but we
SHOULD be able to deal with trailers which were not generated by us.

Specifically, what we want is:

* **Parse trailers**

  Given a `&str`, return an iterator of `(String, String)` pairs, such that:

    * Trailing whitespace at the end of the string slice is ignored
    * Only the last _paragraph_ of the string slice is considered
    * A paragraph is preceded by one or more empty lines (ie. whitespace
      including newlines), and does not itself contain empty lines (but it may
      contain newline characters)
    * The paragraph MUST consist of only trailers
    * A valid key-value pair consists of:

        * A `token`, with no leading whitespace, matching `[-[:alnum:]]+`
        * Optional horizontal whitespace
        * A `separator` (default `:`, _MAY_ be configurable)
        * Optional horizontal whitespace
        * A `value` consisting of UTF-8 characters
        * A newline or EOF

      Multi-line `value`s acc. to RFC 822 "folding" MAY be supported. This is
      expected to be somewhat rare in practice, so not a hard requirement.

* **Replace trailers**

  Given a `&str`, and a list of key-value pairs, return a `String`, such that
  any trailers from the input `&str` are removed, and replaced by rendering the
  supplied list. If the input does not contain any trailers, the supplied ones
  are simply appended as a paragraph. The result must be parseable acc. to
  **Parse trailers**.

**Comment by kim** [comment]
There might be other convenience things we want to layer on top of this, such as `const`s for well-known trailers, a standard way to serialise to a `value`, combinators to manipulate the trailers list. But we'll add them as we go.

**Comment by NunoAlexandre** [comment]
Thanks for this super clear feature spec, @kim!

Just posting some good reads on `git trailers`:

- https://blog.k-nut.eu/extending-git-commits-with-trailers
- https://git-scm.com/docs/git-interpret-trailers
- https://git.wiki.kernel.org/index.php/CommitMessageConventions

**Comment by NunoAlexandre** [comment]
> Unfortunately, `libgit2` doesn't include any functionality for parsing or otherwise manipulating trailers in a commit message.

@kim, it actually does: https://github.com/libgit2/libgit2/pull/4451.
`Git2` doesn't integrate it though.

**Comment by kim** [comment]
Oh TIL. Maybe we can reuse this — adding a binding to `git2-rs` is really easy, and they are very quick to review and accept patches. 

The API doesn’t provide any position information, though, but maybe that’s ok — we don’t need to preserve the commit message, only the trailers.

**Comment by NunoAlexandre** [comment]
> Oh TIL. Maybe we can reuse this — adding a binding to `git2-rs` is really easy, and they are very quick to review and accept patches.

That's good to hear, I assumed that wouldn't be the case. Another consideration: I don't think `git2` offers the **Replace trailer** functionality, so we would still need to implement this bit.

> 
> The API doesn’t provide any position information, though, but maybe that’s ok — we don’t need to preserve the commit message, only the trailers.

Could you expand on what "position information" entails? Not sure I understand :thinking:

**Comment by kim** [comment]
>
> Could you expand on what "position information" entails? Not sure I
> understand 🤔
>
>
If we wanted to replace trailers, preserving the message before them, we
would need to know where the trailers section starts. But now I’m thinking
that we don’t need that — parse array from message1, manipulate, write out
array to message2 should suffice.

>

**Comment by NunoAlexandre** [comment]
> Could you expand on what "position information" entails? Not sure I understand 
> If we wanted to replace trailers, preserving the message before them, we would need to know where the trailers section starts. But now I’m thinking that we don’t need that — parse array from message1, manipulate, write out array to message2 should suffice.
> […](#)

Thanks, I understand now. Yes, that sounds enough and it's also simpler that way.

**Comment by NunoAlexandre** [comment]
Going through https://github.com/libgit2/libgit2/blob/master/src/trailer.c, 6 years after I last touched C, it's non-trivial for me to digest what it offers, especially given that it provides no documentation at all.

An issue that pops the eye is that it hardcodes the trailer separator as `#define TRAILER_SEPARATORS ":"` while the spec says [[0]](https://git-scm.com/docs/git-interpret-trailers#Documentation/git-interpret-trailers.txt-trailerseparators):

<blockquote>
<strong>trailer.separators</strong>

This option tells which characters are recognized as trailer separators. By default only : is recognized as a trailer separator, except that = is always accepted on the command line for compatibility with other git commands.

The first character given by this option will be the default character used when another separator is not specified in the config for this trailer.

For example, if the value for this option is "%=$", then only lines using the format <token><sep><value> with <sep> containing %, = or $ and then spaces will be considered trailers. And % will be the default separator used, so by default trailers will appear like: <token>% <value> (one percent sign and one space will appear between the token and the value).
</blockquote> 

Shall this module offer enough functionality to extract the trailers from a message and to replace trailers in a message, then we can indeed integrate this in `git2-rs` and avoid rewriting this ourselves.

**Comment by kim** [comment]
There isn’t an immediate need for anything but `token: value` trailers, but since the parsing rules trivially also support `Fixes #xyz`, we could just as well provide that. More better ofc if it was just a bunch of parser combinators, but I haven’t tried [nom](https://crates.io/crates/nom) yet, so don’t know how the story is compared to *parsec. Up to you!

**Comment by kim** [comment]
Closed via #271
