### ISSUE TITLE
rustfmt.toml

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#28]
Should we put a `.rustfmt.toml` in the repo?

I found that most of the settings either have reasonable defaults, or aren't usable with the stable toolchain. We may still want to run `cargo fmt --check` on CI, if only to avoid "can you reformat this to 100 instead of 180 colums?" reviews :)

**Comment by xla** [comment]
radicle-dev/radicle-upstream has one. It keeps the tooling consistent.

**Comment by kim** [comment]
You're using nightly.

**Comment by xla** [comment]
Living on the edge!

It's not uncommon, me thinks, to run some of the cargo commands against nightly, even so the project is on stable.
