### ISSUE TITLE
[working copy] Remote Includes

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#287]
The [**Working Copies**](https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/identity_resolution.md#working-copies) section of the identity resolution hints at how we may be able to manage remotes from `librad` as opposed to any upstream clients. The proposal is that it should take advantage of [`git-config`](https://git-scm.com/docs/git-config).

My mini-proposal here is the following. For every `Project` namespace created there MUST be one include file. The include file MUST contain one remote configuration, which is the `rad` remote, i.e. the local peer's remote branch to the monorepo.
The following are operations on the include file:
  * If a **peer** is **added to the remote** of the namespace then we MUST **add it to the include file**.
  * If a **peer** is **removed from the remote** of the namespace then we MUST **remove it from the include file**.

The upstream users of `librad` MAY then include the namespace include file as:
```
[include]
    path = /path/to/<namespace>.inc
```

Suggestions:
* We may want to keep https://github.com/radicle-dev/radicle-link/issues/235 in mind when adding the remotes.
* It would be ideal to have a data structure where we can serialise and deserialise the include data.

**Comment by kim** [comment]
Can you clarify what "add/remove from the remote of the namespace" means?

Also, as hinted at in #235, I am a bit skeptical towards having `librad` manage this -- for one, the instance might be a seed node with a huge tracking graph, which noone ever creates a working copy of. The other issue is that we want these `[remote]` sections for the sole purpose of being able to create a fetchspec which prefixes the peer id with the user name -- now, we would need to update the include file whenever we detect that this name has changed, which is not only annoying to implement (we can't guarantee atomicity), but would also leave dangling remote tracking branches in the working copy (unless the user has configured it to always prune). In other words, it would be less surprising if the _user_ controls when and how the remotes are created/updated, and `librad` provides only convenience methods to generate a config.

**Comment by FintanH** [comment]
> Can you clarify what "add/remove from the remote of the namespace" means?

I meant that if a `refs/remote/<TRACKED_PEER_ID>` was added/removed we would want to add/remove the corresponding remote spec.

 > the instance might be a seed node with a huge tracking graph, which noone ever creates a working copy of.

Good point, so it needs to be optional. So having tools to manage include files is the better route. So really you can disregard my point about adding/removing. What we want is to have some functionality that looks like `generate: Namespace -> Include`, `render: Include -> File`.

We'd still probably want to detect when we have new remote peers in our namespace, or conversely we've removed some peers.

**Comment by rudolfs** [comment]
> In other words, it would be less surprising if the user controls when and how the remotes are created/updated, and librad provides only convenience methods to generate a config.

> Good point, so it needs to be optional.

Thinking about the UX of Upstream -- we could add a checkbox to the checkout modal, something like "keep remotes up-to-date", which would either add or leave out the include in the working directory as a first step.

<img width="40%" alt="Screenshot 2020-08-20 at 15 36 52" src="https://user-images.githubusercontent.com/158411/90776908-ff3b5000-e2fa-11ea-909e-747063b21c5c.png">

**Comment by CodeSandwich** [comment]
I'm not sure what's to be done here. As far as I could understand from the code the monorepo already manages its list of remotes based on its peers on the P2P network. Now the only problem is to make the working copy regularily fetch these remotes, but that's probably up to the upstream?

**Comment by FintanH** [comment]
We want to make it easier to manage the `refs/remotes` in a working copy. It can be handled by upstream but having these tools available in link makes life easier for the users of the protocol :)

I can take over this :+1:

**Comment by CodeSandwich** [comment]
Thank you :+1:
