### ISSUE TITLE
Get project handle by project id (for surfin')

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#29]

**Comment by xla** [comment]
Think we determined to get a `radicle-surf::git::GitRepository`.

**Comment by kim** [comment]
I was thinking more like `librad::project::Project`, which implements some `fn into_browser(self) -> impl surf::Browser` (where `surf::Browser` is not currently a trait, but should be).

**Comment by xla** [comment]
![legit](https://i.kym-cdn.com/photos/images/original/000/264/241/9e9.gif)

**Comment by FintanH** [comment]
> where `surf::Browser` is not currently a trait, but should be

I'm interested to know how this would be more useful than the `struct`?

**Comment by kim** [comment]
@FintanH Well, I wasn't aware that surf requires one to keep a reference to the handle (`GitRepository`), because a `Browser` can only be constructed by reference. That's a bit odd, but I assume there are reasons.

A problem, however, is that we need to hide parametricity, but don't have GADTs. Typically, you'll have a string representation of a project id, which you parse into a `ProjectId` (so this can't be parametric). Then, based on the variant you get, you should be able to open the "right" backend handle, which you can turn into a thing that allows browsing. As it stands, #31 leaks what the backend is, which I think is suboptimal.

**Comment by FintanH** [comment]
> Well, I wasn't aware that surf requires one to keep a reference to the handle (GitRepository), because a Browser can only be constructed by reference. That's a bit odd, but I assume there are reasons.

Ya the issue there is that we need the repository to build up data such as histories. I dunno what the implications are of getting a fresh handle to the repository every time are. Maybe that's a "cleaner" way, and possibly could allow for threading too. 

> A problem, however, is that we need to hide parametricity, but don't have GADTs. Typically, you'll have a string representation of a project id, which you parse into a ProjectId (so this can't be parametric). Then, based on the variant you get, you should be able to open the "right" backend handle, which you can turn into a thing that allows browsing. As it stands, #31 leaks what the backend is, which I think is suboptimal.

Ah I think I understand what you mean, and it;'s a good point :ok_hand:
