### ISSUE TITLE
[applying changes] Relevant peer announcements

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#295]
Currently, when we receive an announcement from the network we will consider it relevant even if the peer isn't one of our tracked remotes.

We would prefer that it wasn't greedy, and rather would only apply changes when it's from a peer that we track for this `RadUrn`, but still gossip the message across the rest of our network.

**Comment by NunoAlexandre** [comment]
So when a node receives an event, we check whether it was emitted by a tracked peer. If it is, we consume it (whatever it means) **and** gossip it around, otherwise, we only gossip around.

Shall my understanding of the problem be correct, we need to look into how gossip events are digested, not necessarily how they are broadcasted.

**Comment by FintanH** [comment]
Ya I believe you'll want to peek around at `LocalStorage`/`PeerStorage`. But maybe @kim can chime in :)

**Comment by kim** [comment]
It is simply the case that a check is missing approximately [here](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L442), which returns `PutResult::Uninteresting` instead of attempting to fetch from the `provider` iff the "origin" peer is not tracked in the context of the base URN.

The "origin" peer is either the same as the `provider`, or the `origin` field of the gossip message if the `provider` is informing us that it now has `origin`s data (ie. `remotes/<origin>/*` in `provider`'s repo).

There is also a simple bool-returning method missing in `Storage` to query if `(Urn, Peer)` is tracked.

**Comment by NunoAlexandre** [comment]
@kim I am confused and unable to make sense of 

> It is simply the case that a check is missing approximately [here](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L442), which returns PutResult::Uninteresting instead of attempting to fetch from the provider iff the "origin" peer is not tracked in the context of the base URN.

The "[here](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/net/peer.rs#L442)" bit points to `Some(Rev::Git(head)) => {` but the rest of the sentence seems to be referring to the previous line, `None => PutResult::Uninteresting,`, where there is no revision, so I am not sure what there would be to fetch?

By the looks of this `fn put`, we would want to do something like `Some(Rev::Git(head)) if is_tracked(&has.urn, &has.origin.unwrap_or(provider))  => {` (pseudo code).

**Comment by kim** [comment]
> By the looks of this fn put, we would want to do something like Some(Rev::Git(head)) if is_tracked(&has.urn, &has.origin.unwrap_or(provider)) => { (pseudo code).

Yep exactly.

Note, however, that the `is_tracked` as currently implemented in #297 is a bit too optimistic I think -- `git2` unifies everything into a single `Error` enum, but we only want to return `false` if the `ErrorCode` is `NotFound`, and otherwise bubble up the error.

**Comment by NunoAlexandre** [comment]
> > By the looks of this fn put, we would want to do something like Some(Rev::Git(head)) if is_tracked(&has.urn, &has.origin.unwrap_or(provider)) => { (pseudo code).
> 
> Yep exactly.

Thanks for the clarification! I am wondering, however, if that piece shouldn't be one level higher, in `handle_gossip`. It appears more adequate to have such check there given the layer of abstraction. I guess the reason we want it in `put` is to be safer in terms of not having the lower layer trusting a higher layer for this matter?

> 
> Note, however, that the `is_tracked` as currently implemented in #297 is a bit too optimistic I think -- `git2` unifies everything into a single `Error` enum, but we only want to return `false` if the `ErrorCode` is `NotFound`, and otherwise bubble up the error.

Good one, will adjust.

**Comment by kim** [comment]
>  I am wondering, however, if that piece shouldn't be one level higher, in handle_gossip.

Not sure what you mean -- the gossip layer has no knowledge about how the messages are dispatched, that's the role of the `LocalStorage` trait. The semantics are: we saw the message before - do nothing; the message is new -- tell others that we now have it; we're not interested in the message -- forward the message to others (the `origin` stays the same, as we don't have it); an error occurred -- request retransmission of the message (up to a limit).

**Comment by NunoAlexandre** [comment]
> > I am wondering, however, if that piece shouldn't be one level higher, in handle_gossip.
> 
> Not sure what you mean -- the gossip layer has no knowledge about how the messages are dispatched, that's the role of the `LocalStorage` trait. The semantics are: we saw the message before - do nothing; the message is new -- tell others that we now have it; we're not interested in the message -- forward the message to others (the `origin` stays the same, as we don't have it); an error occurred -- request retransmission of the message (up to a limit).

That answers it :open_umbrella: 

> > > By the looks of this fn put, we would want to do something like Some(Rev::Git(head)) if is_tracked(&has.urn, &has.origin.unwrap_or(provider)) => { (pseudo code).
> > 
> > Yep exactly.

I have done just that in https://github.com/radicle-dev/radicle-link/pull/297/commits/86cc0610b8f26cb44bd45a66846f394c0682c8e9. That seems to address the original issue or am I missing something?
