### ISSUE TITLE
Hide non-humane branches from surf

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#30]

**Comment by FintanH** [comment]
What was the issue here again? :joy:

**Comment by kim** [comment]
We wanted to hide the branch naming conventions from the library user. This
seems to become a non-issue, because we concluded in #65 that the "identity
branch" would always be `rad/id`, and other branches (such as issues) may not
even be hidden (even though they may not be meaningful to browse).

**Comment by FintanH** [comment]
Mmmmk, would you rather close it now or wait until we've finished the work on identities to see if it's a true issue?

**Comment by kim** [comment]
I think it should probably still not be up to string-matching which branches are surfed. Renamed the ticket.

**Comment by FintanH** [comment]
Well, it's going to come down to string matching because libgit only allows filtering on local or remote. But I think I understand what you mean. Do you think this ticket should be in surf though?

**Comment by kim** [comment]
Should no longer be an issue, as long as `surf` hides the `refs/rad` hierarchy.
