### ISSUE TITLE
Extend API to get all metadata filtered by a specific PeerId

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-link#306]
To drive a bunch of use-cases it could be helpful to have a way to get the list of metadata filter by PeerId. Besides what @FintanH mentioned in https://github.com/radicle-dev/radicle-upstream/pull/866#discussion_r483103462 - we could also add an optional to `all_metadata` to filter directly.

**Comment by kim** [comment]
Based on the linked thread, it seems to me like what you want is not to descend into the `remotes` hierarchy of a project, but to filter on absence or presence of `rad/signed_refs`. Getting some `PeerId`'s view of the metadata would just yield unverified data which may be ahead or behind of what the local peer has committed to.

Iow, the query is more like

```sql
SELECT ns.rad_id 
FROM namespaces 
LEFT JOIN namespaces AS ns ON ns.namespace = namespaces.namespace
WHERE 
  EXISTS(namespaces.namespace("refs/rad/signed_refs"))
```

(if my memory of SQL serves me right lol)

So, what we want is a reference filter which allows to `*` the namespace. Something like this imaginary code:

```rust
impl Storage<yadda> {
    fn monowide_references_glob(
        &self,
        glob: AreWeTypesafeYet,
    ) -> Result<impl Iterator<Item = NamespacedRef>, Error> {
        References::from_globs(&self.backend, [format!("refs/namespaces/", glob)].iter())
    }
}

/////

use itertools::Itertools;

storage
    .monowide_references_glob("*/refs/rad/signed_refs")?
    .unique_by(|nref| nref.namespace())
    .map(|nref| storage.metadata(Urn::from(nref.namespace())))
    .collect::<Vec<_>>()
```

**Comment by FintanH** [comment]
In general, we'd like to be able to get monowide things for peers. Like in the case of a "user profile" which is all the projects for some PeerId. And it seems the above would be able to do that too :)

Aside: should we build a DSL to query git references :eyes:

**Comment by kim** [comment]
> should we build a DSL to query git references

AreWeTypesafeYet?

**Comment by FintanH** [comment]
> AreWeTypesafeYet?

**No.**

**Comment by FintanH** [comment]
> But.. this doesn't make sense. There are only the projects of the local PeerId. If you want the "user profile" of a PeerId, then you need to know the Urn of a User-typed repo which happens to have that public key in its trust delegations.

Ach, you're right. I was thinking if we have the PeerId we just ask for all the projects where we have a remote with that PeerId.

At the moment it's implemented by having the Urn and going through all projects for each project go through the remotes. For each remote check that rad/self is the same as the Urn.

So, I was hoping having the PeerId so that we could just get the remotes directly.

**Comment by kim** [comment]
> I was thinking if we have the PeerId we just ask for all the projects where we have a remote with that PeerId.

What I don't understand is, what do you do with that information? Afaics, the return type is the project metadata. And having a remote with a specific `PeerId` means that this `PeerId` is in the tracking graph for that project. If you want to show the profiles (user metadata) of all the people you track in some way, you need to iterate over `all_metadata`, filtered by type.

**Comment by FintanH** [comment]
> What I don't understand is, what do you do with that information? Afaics, the return type is the project metadata. And having a remote with a specific PeerId means that this PeerId is in the tracking graph for that project. If you want to show the profiles (user metadata) of all the people you track in some way, you need to iterate over all_metadata, filtered by type.

Sorry, maybe I didn't explain it right. The idea is that we have a screen that shows what projects you and another user have in common (according to your monorepo). The words "user profile" were probably misleading in that you were thinking of displaying the user's metadata.

Does that make more sense?

**Comment by xla** [comment]
@kim For some visual illustration a comparable view would be https://github.com/cloudhead?tab=repositories

**Comment by kim** [comment]
> what projects you and another user have in common

But we don't have this information, because we don't know all the projects of that other user. If what @xla is alluding to is the "Forked from" line, then it's checking if your own `PeerId` is in the delegations of the project identity you're looking at.

**Comment by FintanH** [comment]
> But we don't have this information, because we don't know all the projects of that other user. If what @xla is alluding to is the "Forked from" line, then it's checking if your own PeerId is in the delegations of the project identity you're looking at.

We don't know _all_ the projects, but we do know the subset of projects that we share if they're a remote of a project in our monorepo.

For example, say if I replicate a project from you. Then I have the project in my monorepo and you're a remote under that namespace. If I then "click on your user" it will show that project, since I know you have it due to you being in my remotes. But maybe I replicated other projects from you. It would be the same story, so I see multiple projects in this view of you.

**Comment by kim** [comment]
Not sure this is relevant anymore. We have support for [globbing](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/storage.rs#L228) across namespaces if it is.
