### ISSUE TITLE
Cannot create include files on NixOS

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#337]
The error:
```
Include(Io(Os { code: 18, kind: Other, message: "Invalid cross-device link" })))
```

Relevant documentation: https://doc.rust-lang.org/std/fs/fn.rename.html#platform-specific-behavior.

It's possible that my tmp is mounted on a different `dev` and so when we try to create a tmp directory and rename it to the git-include location it fails with the above.

**Comment by kim** [comment]
> It's possible that my tmp is mounted on a different `dev`

Oh yeah, and that's very common. The fix is to use `tempfile::tempfile_in`.
