### ISSUE TITLE
Make PublicKey Copy

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#348]
It was a n00b oversight to not derive `Copy` for `PublicKey` (and, by extension,
`PeerId`). It is almost always impractical to pass those types around by
reference, and given it's only 32 bytes not really worth the trouble.

Deriving `Copy` will create screenfuls of linter warnings, though.

**Comment by FintanH** [comment]
![linter is coming](https://i.imgflip.com/4hi0jo.jpg)

Strong Clippy Vibes
