### ISSUE TITLE
Known-valid refnames

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#380]
In order to avoid runtime `.unwrap()`s of known-to-be-valid `RefLikes`, we
should figure out how to write a proc-macro to turn a string literal into a
`RefLike` at compile time.

**Comment by kim** [comment]
"Function-like proc-macros" can only output a `TokenStream`, so afaiu this would merely allow to evaluate `RefLike::try_from(x).unwrap()` at compile-time, and then quasi-quote the exact same thing (ie. evaluate **both** at compile- and runtime). But better than maintaining pointless test cases which ensure the conversion doesn't panic, I guess.

**Comment by FintanH** [comment]
So if it wasn't valid the `unwrap` would complain at compile-time, and then realistically we wouldn't run into that panic at runtime?

**Comment by kim** [comment]
Yeah, unless the `TryFrom` impl is non-deterministic :joy:

**Comment by FintanH** [comment]
I tried this out and it didn't seem to fire at compile time. I was playing around as much as I could and here were some examples:

```rust
#[macro_export]
macro_rules! reflike {
    ( $raw_reflike:expr ) => {
         RefLike::try_from($raw_reflike).unwrap()
    }
}
```

```rust
#[macro_export]
macro_rules! reflike {
    ( $raw_reflike:expr ) => {
        {
            let raw: &str = $raw_reflike;
            match RefLike::try_from(raw) {
                Ok(reflike) => reflike,
                Err(err) => {
                    println!("Failed to parse RefLike: {}", stringify!(err));
                    compile_error!("Failed to parse RefLike")
                },
            }
        }
    }
}
```

Admittedly, no idea what I'm doing so gonna give up for now :shrug:

**Comment by kim** [comment]
What this does is to splice in the AST fragment in the match arm -- it doesn't
_run_ it. We'd need a "function-like procedural macro", which have the type `fn
lemacron(i: TokenStream) -> TokenStream`. Inside that function, you have
unconstrained effects. If it panics, that'd be a compile-time error (afaiu).

**Comment by FintanH** [comment]
That makes sense :+1: Guess I need to hit the books again
