### ISSUE TITLE
Better confirmation message for correct git-remote-rad installation?

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-link#402]
As I dive into user documentation, I have been building out a section called "Configuring your system", which outlines the steps for configuring a user's shell with the Radicle remote helper. They are as follows:

- Add ` export PATH="$HOME/.radicle/bin:$PATH" ` to your shell configuration
- Restart your shell
- Check that you've done everything correctly by running `git-remote-rad` in your shell. You should receive something along the lines of:

```
~ git-remote-rad
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/buildkite/buildkite-cache/cargo/git/checkouts/radicle-link-009c17032bc5eda9/577e994/git-helpers/src/remote_helper.rs:42:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
```

The resulting "confirmation" message is a bit convoluted — is there any way we can make it more user friendly? Not sure what the constraints on the message are @kim

**Comment by FintanH** [comment]
The `git-remote-rad` isn't meant to be used by a user. It's called by hooks from the `git` CLI. If they want to confirm that it's avaliable in their path a user can run (and see the output):
```bash
$ which git-remote-rad
<home path>/.radicle/bin/git-remote-rad
```

**Comment by abbey-titcomb** [comment]
Great! This is *much* better. I will change it as so.
