### ISSUE TITLE
Tracking own PeerId

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#410]
While testing the Upstream application we noticed that it's possible that one can end up tracking their own remote. This was surfaced when collaborating between 3 peers and a seed.

**Comment by kim** [comment]
Can you describe what "tracking their own remote" means?

**Comment by FintanH** [comment]
So in the monorepo layout I ended up with entries under:
```
refs/namespaces/<id>/refs/remote/<my peer id>
```

**Comment by kim** [comment]
I don't really have an idea how this can happen -- tracking checks if you're attempting to track your own peer id, and network connections to yourself should be rejected on the TLS layer already.
