### ISSUE TITLE
User URNs are not fetched

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#420]
When tracking remotes for a project we are fetching their version of the project, but we aren't fetching their users.

In the example below, this was a session where I replicated one project, and have 4 remotes, one of them being the maintainer. The other two top-level namespaces are my own user and the maintainer's user. The rest do not have an associated user in the monorepo.
```
/home/haptop/.local/share/radicle/git/refs/
├── heads
├── namespaces
│   ├── hwd1yrebytzk4zf7uthifyyqp6umdxninhxux5g95a8868bhqda6bkrrhuw
│   │   └── refs
│   │       └── rad
│   │           ├── id
│   │           ├── self
│   │           └── signed_refs
│   ├── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│   │   └── refs
│   │       ├── rad
│   │       │   └── id
│   │       └── remotes
│   │           └── hydk3srgfsekrwreyedqpgf7mf48ccgkt73heoejo18afe6cdkapeq
│   │               └── rad
│   │                   └── id
│   └── hwd1yrer3ok6h1srbir4ps15twrhnk1sobpukkufif9aba474f5ntwqyh6h
│       └── refs
│           ├── rad
│           │   ├── id
│           │   ├── ids
│           │   │   └── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│           │   ├── self
│           │   └── signed_refs
│           └── remotes
│               ├── hydf1xhgdqey436xsaxf5bbjt7agfqxeztcgdfuk71h7wziy9foudy
│               │   ├── heads
│               │   │   └── main
│               │   └── rad
│               │       ├── id
│               │       ├── ids
│               │       │   └── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│               │       ├── self
│               │       └── signed_refs
│               ├── hydk3srgfsekrwreyedqpgf7mf48ccgkt73heoejo18afe6cdkapeq
│               │   ├── heads
│               │   │   └── main
│               │   └── rad
│               │       ├── id
│               │       ├── ids
│               │       │   └── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│               │       ├── self
│               │       └── signed_refs
│               ├── hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw
│               │   └── rad
│               │       ├── id
│               │       └── ids
│               │           └── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│               └── hyyz1iu3oampm7pupugbjwupjm48auxcb5fby554uy4yhhsgu4xrsr
│                   ├── heads
│                   │   └── main
│                   └── rad
│                       ├── id
│                       ├── ids
│                       │   └── hwd1yregqmmerej8ma4fkwq1mtqiiz79qkehba8q7ykne7msfzb9q34mg6a
│                       ├── self
│                       └── signed_refs
└── tags
```

**Comment by kim** [comment]
> In the example below, this was a session where I replicated one project,
> and have 4 remotes, one of them being the maintainer.

Are the remaining 3 directly or transitively tracked?

**Comment by FintanH** [comment]
Directly tracked, i.e. they're tracked by calling `storage.track`

**Comment by kim** [comment]
This is not technically a bug: you are tracking a project, not a person. The fact that you know one or more `PeerId`s, whose views on the project you're interested in, implies that you _might_ also be interested in _some_ identity which delegates to those `PeerId`s (that's potentially where you got them from). But it does not imply that you are automatically interested in replicating this identity -- this is why we have `rad/self`, which is only the minimal data needed to reify what top-level identity this peer is impersonating as.

Iow, if you also want the animated gifs and whatnot of those people, you need to explicity track what `rad/self` points to.

**Comment by FintanH** [comment]
Alles klar, my misunderstanding so :+1: I'll move the ticket to upstream since we want those sweet gifs there
