### ISSUE TITLE
net: terminate connection when idle

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-link#437]
Currently connection are kept, even when all streams finished/errored. It should be considered to review that behaviour.

Ref https://github.com/radicle-dev/radicle-link/pull/434#issuecomment-732239507

**Comment by kim** [comment]
My current thinking is that they should be kept, even when demoted to the passive view. The idea is that this should be _relatively_ cheap (as opposed to TCP), and with keep-alive probes just frequent enough to prevent middleboxes from dropping NAT bindings, a `Shuffle` response would mean that the responder will be able to assist in hole punching whp.

There are a few prerequisites:

* The membership should only retain peers whose set of tracked peers has a non-empty intersection with the local set (it took me a while that this doesn't need to take repos into account)
* The passive view should be bounded, and connections dropped when the peer is _neither_ in the active nor passive view
* A tad bit more control over how and when `PING` frames are sent would also be nice

**Comment by kim** [comment]
This is done as of `net/next`. Connections are closed when no longer in the partial view, and inactive for idle timeout (regardless of PING frames).
