### ISSUE TITLE
Running tests on windows fail due to path separators on RefLike urn tests

### ISSUE THREAD

**Issue by bltavares** [radicle-dev/radicle-link#467]
It looks like the RefLike and other structures on `name.rs` use interally a `PathBuf` which changes how it behaves when running on windows.

```rust
pub struct RefLike(PathBuf);
```

```
---- identities::urn::tests::is_reflike_with_path stdout ----
thread 'identities::urn::tests::is_reflike_with_path' panicked at 'assertion failed: `(left == right)`
  left: `"hnrkyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/refs/heads/lolek/bolek"`,
 right: `"hnrkyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy\\refs/heads\\lolek/bolek"`', librad\src\identities\urn.rs:485:9
```

All the tests failing on the repo are due to using the `/` separator on tests directly, but further inspecting the code, we have a few other places which assumes the `/` separator, even tho it's a pathbuf internally.

I'm not sure what the best course of action is here - there is a lot of places using PathBuf internally and I'm not sure if we only need to change the `RefLike` join would be enough

**Comment by kim** [comment]
Ouch.

I was just pretending the day we needed to support windows would never come :innocent: 

It _should_ be that all values which need to be converted to a git reference(-pattern) go through the types in `git-ext::reference::name` (if not that's a bug), so changing the internal representation should be enough.

**Comment by bltavares** [comment]
I'm trying to do some fixes over the day and run the tests - which are very tricky... - but I'll share a PR when I have things green
