### ISSUE TITLE
Use more descriptive repo description

### ISSUE THREAD

**Issue by hoijui** [radicle-dev/radicle-link#477]
That way, one knows what this is, when looking at the list of repos under this organization.

**Comment by kim** [comment]
Thanks for your feedback. Feel free to submit concrete improvement proposals. I also suggest to check out https://github.com/radicle-dev/radicle-docs resp. https://docs.radicle.xyz

**Comment by hoijui** [comment]
*the Radicle code collaboration protocol and stack*
