### ISSUE TITLE
Consolidate crypto

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#52]
We have accumulated a somewhat worrying proliferation of low-level crypto libraries already:

* [sodiumoxide](https://crates.io/crates/sodiumoxide) (`libsodium`)
* [nettle](https://crates.io/crates/nettle) -- via [sequoia-openpgp](https://crates.io/crates/sequoia-openpgp)
* [ring](https://crates.io/crates/ring) -- via [rustls](https://crates.io/crates/rustls), [rcgen](https://crates.io/crates/rcgen), and [webpki](https://crates.io/crates/webpki)
* [openssl-probe](https://crates.io/crates/openssl-probe), [openssl-sys](https://crates.io/crates/openssl-sys) -- via [git2](https://crates.io/crates/git2)

The last one is easy to fix: just turning off the `ssh` feature of `git2` should suffice. `sodiumoxide` we should also be able to replace with any `ed25519`-capable library -- except that we're currently using its convenient KDF facilities to encrypt key material on disk.

The remaining ones are a bit tricker: it's unlikely we can get rid of `ring` (unless we can get rid of TLS). There is, however, an alternative to `sequoia-openpgp` which I totally missed out on: [pgp](https://crates.io/crates/pgp). I think it's not quite as comprehensive as sequoia, but should do for our purposes -- assuming that, even if we end up not signing any git commits ourselves, we still need to be able to verify them. It uses [ed25519-dalek](https://crates.io/crates/ed25519-dalek) under the hood, though, so we'd still have to live with two different `ed25519` implementations.

**Comment by kim** [comment]
`nettle` is gone

**Comment by xla** [comment]
Didn't we achieve obliteration of sodiumoxide recently?

**Comment by kim** [comment]
Ya, don't think we can do much better.

One thing to note is that it is quite laborious to convince cargo to not sneak in the `ssh` feature of `git2`. I think `cargo deny` can prevent it, but we'd need to establish it in all projects. (Nb. `openssl` is not compatible with GPL, even though the crate is licensed differently).
