### ISSUE TITLE
Feature Branches

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#56]
Something that came up during one of our conversations that I wanted to discuss and keep track of was: What are the semantics of a feature branch?

When a user wants to work on a particular feature on a radicle project how do they set that up for collaboration?

I think my current understanding is:
* Create a branch under the rad scheme
* This gets picked up by other peers that are tracking you
* You track their changes in turn

Where I get fuzzy is how do these changes become verified by the maintainers of the project? What would a merge into `master` look like?

**Comment by kim** [comment]
Are you referring to code branches? This works exactly like anywhere else: the branch shows up under the author's namespace (`remotes/author/fix/make-bananas`). Someone decides to merge that into their local `master`, which in turn shows up as `remotes/author/master` to others. If "someone" happens to be a maintainer, everyone else should base their next feature branch off of this.

**Comment by FintanH** [comment]
Ah cool! Thought it might have been more complicated for some reason. Makes sense :ok_hand:
