### ISSUE TITLE
Allow advertising predefined address

### ISSUE THREAD

**Issue by viraptor** [radicle-dev/radicle-link#584]
Not sure if this belongs just to -bins or does it extend to -link, but just like the webserver has a listen and a public address, radicle should have the same option. Currently I'm seeing advertisements from my seed like this:
```
 2021-04-05T15:38:20.333 INFO  librad::net::protocol::membership::hpv      > apply; remote_peer=hybk76pim74znj9tapyarr3qmxt1qyc9u1rfk9cda63pdsq9rrz8o4 remote_addr=35.197.169.21:12345 rpc=Neighbour { info: PeerAdvertisement { listen_addrs: {10.152.0.4:12345}, capabilities: {} }, need_friends: None }
```
However that seed is never going to be reachable for others on the `listen_addrs`.
(Bonus points for discovery via STUN https://crates.io/crates/rustun)

**Comment by kim** [comment]
> just like the webserver has a listen and a public address, radicle should have the same option

Yeah, not a bad idea. If you want to give it a spin, the net::peer::Config would be a good place to start.

> However that seed is never going to be reachable for others on the listen_addrs.

That’s not universally true, though: a regular p2p node could very well wish to be reachable on the local network, and NAT hairpinning behaviour is not something we could reliably detect. Peers will add the address they see the other end as before propagating peer information, so the advertised address is not the only option.

That being said, a config option to turn off advertisement of a private address in case you know what you’re doing isn’t a bad idea either.

> Bonus points for discovery via STUN

STUN only works when both ends agree on a well-known server — which is not exactly what we mean when we say “decentralised”. So... if you have a proposal of how to run an open STUN network which incentivises people to participate, converges towards a set of honest, reliable, and properly configured nodes, and yields overall lower latency and higher success rate than the brute force method of just trying all addresses a node _appears_ to have (considering that STUN is basically a brute force method of trying all addresses a node _appears_ to have), I would be very interested to hear it ;)

**Comment by viraptor** [comment]
> a regular p2p node could very well wish to be reachable on the local network

Correct, I wouldn't want to remove that option. I meant *that specific* node will never be reachable that way.

> the net::peer::Config would be a good place to start

Thanks, I will have a look.

> STUN only works when both ends agree on a well-known server

We could still use a very limited part of stun. Only the "query for address" functionality, where it's up to the local node to decide who to ask. (With some sane default)

**Comment by kim** [comment]
> We could still use a very limited part of stun. 

Here's how this works currently: the receiver of a membership control-message adds the address it sees the peer as to the `seen_addrs`. When a shuffle occurs, this information gets propagated. When a peer tries to connect to another peer it hasn't been connected to (modulo eviction from the partial view), it will try `seen_addrs + advertised_addrs`, and pick the first one to succeed.

Obviously peers could be lying, and it _may_ improve cold-start performance if the partial view was persisted to disk on shutdown. 

> the "query for address" functionality

I don't understand what you mean by that. _When_ should we query for our own address? If we are able to establish an outgoing connection, the other end will propagate the "real" address.

That doesn't help of course if we're behind an endpoint-dependent NAT, but then, hole punching won't work anyways. The only tricks I'm aware of to deal with this involve coordinating through a third machine -- to which, crucially, the other two must be connected at the same time.

So, the only way I could see this working is to adjust how shuffling works: whenever a shuffle _request_ is received where `origin == remote_id`, we assume that the remote is currently connected to (most of) the offered peers, and thus can act as a coordinator. The shuffle receive would then attempt to establish connections eagerly, using the coordinator to eg. conduct a search for neighbouring ports (I don't think TURN-style relaying is something we'd want). Those connections would just sit there until they are either requested by the protocol, or time out.

I'm not sure how to measure or to even observe that this would be beneficial overall, so haven't attempted anything to this end yet =]

Tagging #66 and #594
