### ISSUE TITLE
Policy: to mod or not

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#64]
I can't tell what is currently considered "idiomatic" wrt `mod.rs` files, and source tree structure in general. I've been using `mod.rs` files without being aware that they were no longer required, and I always found them quite odd.

Shall we just settle to remove them entirely, and use the more intuitive `mymod.rs` / `mymod/mysubmod.rs` everywhere?

**Comment by FintanH** [comment]
It's official since [Rust 2018](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs). I say we burn the `mod.rs` files and use the intuitive way :)

**Comment by xla** [comment]
🔥🔥🔥

**Comment by kim** [comment]
Any volunteers for operating `git mv`?

**Comment by FintanH** [comment]
Ya I'll take it on
