### ISSUE TITLE
Uniform Resource Locators

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#65]
## Objective

Formal definition of a URI/URN scheme for entities (tbd) in the radicle network.

### "Physical" Addresses

`radicle-link` can be seen as a forest of **projects**, where the stable **project identifier** maps to a repository name. The "physical" address, however, is in the context of a currently connected-to peer:

`rad://PEER_ID/PROJECT_ID`

where the network address mapped to the `PEER_ID` is transparently handled by the networking layer.

This is so because we are **not** employing a DHT-based network -- the reasons for this are outside the scope of this discussion, but the short answer is that for this to perform acceptably, one has to assume at least `R` permanently connected nodes, where `R` is the replication factor. This is one of the main issues with IPFS.

The path components _after_ `PROJECT_ID` are implementation-defined: in `git` and `pijul`, we can physically address down to named-branch (`ref`) level. `git` actually negotiates the mapping from name to head hash, so in principle it is also possible to content-address the branch. It is **not** currently possible to address down to tree- or blob-level, because the merkle proof of the result requires a commit object. `pijul` could, in principle, address individual patches, but that functionality is not provided as of this writing (and it's also unclear what the benefits would be).

### Logical Addresses

Logically, we want to address:

* **projects**
* **identity documents**, along with their history
    
    The well-known identity documents are those of a **project** and a **user**, but we can generalise this to any document validated by the TUF rules, e.g. modelling ACLs.

* documents containing **signatures over the advertised `refs` of a peer** 
* histories with application-defined semantics, e.g.
  * **issues**
  * **pull requests** ("revisions")
  * **activity feeds**
* histories without interpreted semantics, i.e. **code branches**

All of these have in common that they are named roots of merkle DAGs,e xcept for projects, which are named _forests_ of merkle DAGs. Somewhat unclear is how **strongly bound** some of them are to the context of a **project**. Specifically, the **user identity** is supposed to be globally stable. One might expect, for example, to navigate to the **activity feed** bound to a **user**, without knowing the "canonical" **project** that user is bound to. Also, **issues** (isomorphic to revisions, but without references to code) could arguably appear within _any_ project, while semantically describing a different one.

_Note: a non-issue in this context is that two different projects could be names for the same, well, object database. They could be seen as forks in the original sense of the term, but be combined into the same local checkout as different remotes._ 

## Solutions

1. Overload the project identifier

    Currently, we have `HASH(metadata) '.' STORAGE_BACKEND`. This could be generalised to:

    `VARINT_TYPE_TAG:PAYLOAD[:VARINT_TYPE_TAG:PAYLOAD] `

    This would result in potentially very long identifiers.

2. Interplanetary Merkle-DAG

    Essentially, a global namespace where every node is content addressed. This is what IPFS does, and is a non-solution: we are in all cases interested in the _most recent, named head_ of a history leading back to a well-known "genesis" node. This requires an external naming system, or a DHT. The latter is called IPNS in the IPFS world, and predictably (and unsurprisingly) times out after 10s of minutes.

3.  Local indexing

    Preserve the project semantics ("just a name for a bunch of branches"), but locally maintain an inverted index `identifier -> project/path` as they are discovered. The local node should be able to answer queries from the network for this mapping. 

    Identifying what is an identifer (hah) needs to resort to convention. For example, a branch prefix like `.rad/identity/` could treat everything below as an indexable identifier, without knowing what kind of identifier. This is bounded by `PATH_MAX` on Linux (which is 4096 chars last time I checked), and probably some incomprehensible behaviour on Windows. That should still be enough, as I can think only of two levels atm: `user`, `user/{feed,..}`.

**Comment by kim** [comment]
Summary of RTC discussion between myself, @massimiliano-mantione and @FintanH, with some details and questions filled in by yours truly:

We generalise the notion of **identity** documents to include both **projects** and **users**, and possibly something else in the future. Their stable identifier (content hash) shall be resolvable as a top-level entity -- this means that the name of the **repository** can be _any_ **identity** hash, not just a **project ID**. More formally, the shareable form of a `radicle-link` URI is:

    rad://[human-readable-name@]MULTIHASH/path/to/branch

On the p2p network, this will eventually be resolved into a URI of the form:

    rad://PEER_ID/MULTIHASH/path/to/branch

The second form may be surfaced to the user for use cases in which the peer identity has been verified (and trusted) out-of-band, e.g. seeds.

**Notes**

* The branch name cannot be optional, because it is not always possible to infer from the context what type of identity the hash describes, and thus apply a naming convention
* It remains possible to scope an identity below another one, e.g. to store user identities within the context of a project

**Open Questions**

* As an optimisation, it was proposed that peers maintain a dedicated repository containing all identity branches as they are discovered. This way, a peer can fetch multiple such branches with 2RTT (one `git` fetch). However, this dictates `git` as the only backing store.

* Likewise, the content hash does not include any information about the backing store -- if we were to support more storage options, this would require a client to support all of them. Also, a content negotiation step would be required, imposing min. one additional RTT.

* Scoped branches with a stable identity need to convey the root hash somehow. One way is to encode it in the branch name, e.g.:

        rad://<project hash>/.rad/contributors/<user hash>

  which may impede navigation by humans. Another way would be to use anchors (which also aptly describes what the purpose is):

        rad://<project hash>/.rad/contributors/kim#<user hash>

* It was proposed that the human readable name must match a value in the identity document, and thus the name cannot change over the lifetime of the entity. Why exactly do we need this?

* Not encoding any content type information in the `MULTIHASH` contradicts that clients _do_ actually want to distinguish them when discovering what a remote peer serves (i.e. list projects, list users). The cheapest way I can think of this can be provided is to store both types under a different directory each, e.g. `projects/`, `users/` (see also #58). But then, why not retain a flat namespace, but make it so the _client_ can filter by type (that is, prepend a varint to the hash which tells us what it describes)?

**Comment by kim** [comment]
@massimiliano-mantione I fear that those questions are on you :)

**Comment by massimiliano-mantione** [comment]
> The branch name cannot be optional, because it is not always possible to infer from the context what type of identity the hash describes, and thus apply a naming convention

This is not necessarily true: the naming convention could imply one single "canonical entity" per git repository.
For "project" repos it would be the project, for "user identity" repos it would be the user.

Other entities in the repo would necessarily be "scoped" (contained) ones, which I think is a good thing.

> As an optimisation, it was proposed that peers maintain a dedicated repository containing all identity branches as they are discovered. This way, a peer can fetch multiple such branches with 2RTT (one git fetch). However, this dictates git as the only backing store.

I think the backing store could be different.
See more about this in #58.

> Scoped branches with a stable identity need to convey the root hash somehow. [...]

:+1: 

> It was proposed that the human readable name must match a value in the identity document, and thus the name cannot change over the lifetime of the entity. Why exactly do we need this?

There are two conflated issues in this proposal, which I wrongly did not distinguish.

One is the addition of the "name" to the hash, another is eventually making the name immutable.

The main goal is to make URNs more human readable: a hash is meaningless for a user, while a regular name is more recognizable.
So, given a hash `qwertyuiop`, the idea would be to allow to resolving `rad:massi@qwertyuiop` as `rad:qwertyuiop`, and then fail the resolution if the entity name is not `massi`.

So, to state it clearly, the `<name>@` section is entirely optional and would not affect the "transport" part of the resolution.
The final check on the correctness of the name would be performed so that users cannot be fooled by URNs showing wrong names.

Now, the fact that the name is immutable between entity revisions, or that it must simply match the name of the last known revision (the one actually resolved to), would be an open question.
Thinking better I would leave names mutable over time, the first part of this proposal could still be useful.

**Comment by kim** [comment]
> So, given a hash `qwertyuiop`, the idea would be to allow to resolving `rad:massi@qwertyuiop` as `rad:qwertyuiop`, and then fail the resolution if the entity name is not `massi`.

It's an interesting idea -- I remember now: the reason the name cannot be mutable is that _old_ URNs would be invalidated when the name changes. This could be a good thing when clicking on a link, but a bad thing when that link is rendered from a persistent historical state (of an issue, f.ex.). Iow, it seems tricky when and when not to apply the verification. Pinging @cloudhead

**Comment by cloudhead** [comment]
My inclination would be to *not* verify the name at the protocol layer, and treat it simply as a label. At the app layer, we can decide whether to make it a warning or simply ignore mismatches. But it could be something like "Warning: this user's current name is not @<label>, proceed with caution."

Which kind of makes me wonder if this need to live at the protocol level at all. Ie. if there's any form of human-friendliness that we can verify at this level :thinking:

**Comment by kim** [comment]
Yeah I agree. But I then also don't see why we should allow this to "steal syntax" at all -- a shareable identifier `massi@qwertyuiop` simply gets transformed into `rad:qwertyuiop`.

**Comment by kim** [comment]
>  the naming convention could imply one single "canonical entity" per git repository.

I'm ok with this: we simply say `rad/id` is the canonical branch. As @cloudhead pointed out, this also frees up some forward slashes which we can use to reference _other_ things under that identity, e.g. `rad:<project>/issues`.
