### ISSUE TITLE
Networking: mDNS discovery

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#67]
`Discovery` should be a monoidal datatype instead of a trait, and yield an asynchronere stream of `(PeerId, SocketAddr)` pairs. One challenge is to deduplicate this stream, as mDNS will discover the same link local responders with every query.

Implementation wise, the crate situation isn’t great: the [mdns](https://crates.io/crates/mdns) crate looks ok, but only provides a client, [libmdns](https://crates.io/crates/libmdns) only the responder side (with a futures 1 interface, which isn’t great). Others either seem to have native dependencies, or are in some way non-standard. A generic, high quality DNS library doesn’t seem to exist. Potentially the best strategy would be to steal the DNS types from libp2p, and inline them.

**Comment by massimiliano-mantione** [comment]
> Potentially the best strategy would be to steal the DNS types from libp2p, and inline them.

If this is really the best strategy, maybe a second step would be:

* extracting them into a crate
* propose a pull request to libp2p so that it uses that crate
* if they accept it, let the libp2p maintainers also maintain that crate (they were maintaining the original code anyway)

**Comment by kim** [comment]
Ya, although I have somewhat little hope they would be interested in this. After a second look at `mdns`, I think it exports enough to build a responder. We can then ask the maintainer if they'd be interested to upstream that.

**Comment by kim** [comment]
#459
