### ISSUE TITLE
Intercept git push

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#73]
Currently, we set up a `rad` remote for a local git tree with some specially crafted fetchspec which rewrites code branch names to be prefixed by `src/` and radicle ones by `rad/`. That's very fast, because git will hardlink object database files where possible, as it can see that it's a local `file://`. We may, however, want to rethink this brach naming convention, and also whether or not it should be visible to users where the "hidden" git repo is located.

Also, we may want to run some code whenever the user runs `git push rad` in the working tree: update the signatures on the `refs` (which may require prompting for a keystore passphrase), connect to the network and publish the updates (what if that fails?). 

_Potentially_ a `pre-receive` hook in the hidden repo would do, otherwise we may need a [remote helper](https://git-scm.com/docs/gitremote-helpers).

**Comment by FintanH** [comment]
The story here has changed _slightly_ because of the namespace RFC, but the remote helper is still relevant. We have an issue with DWIM when it comes to `<branch>` vs. `refs/heads/<branch>` and having it push to the `rad` remote.

As well as this, the remote hook could prompt for signing refs (correct me if I'm wrong, @kim)

**Comment by kim** [comment]
Yes, the implementation has changed, but we can still keep this as a
tracking issue.

**Comment by FintanH** [comment]
> still keep this as a tracking issue.

Ya, sorry that's what I meant, but didn't actually say :sweat_smile:

**Comment by cloudhead** [comment]
Having a remote helper would also mean we could get away with not having a ‘checkout’ cli or button, right?

**Comment by kim** [comment]
Closed via #233
