### ISSUE TITLE
Time out when establishing connection to peers

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-link#737]
Establishing a QUIC connection to a peer should time out when the peer does not respond. This should probably be added to `librad::net::protocol::io::connection::connect()`.

**Comment by kim** [comment]
Last time I checked, quinn times out connection attempts. Feel free to reopen if you have more info which shows that is not true

**Comment by geigerzaehler** [comment]
You’re right. I times out, just after more than a minute though. This is why I didn’t see it.

**Comment by kim** [comment]
I think it is the same timer that is also used for packet loss detection. Not
sure if this is mandated by QUIC, or could be a separate tunable.
