### ISSUE TITLE
Git storage file system watcher is leaked

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-link#750]
librad leaks file system watchers. When a librad `Peer` is dropped there remain threads which watch the file system. When a lot of `Peer`s are created e.g. in tests this leads to “Too many open files” errors. This issue may also cause “Bad file descriptor errors” upstream is seeing on CI.

The leak is caused by spawned threads here https://github.com/radicle-dev/radicle-link/blob/bfdc3ec0c7ba542f2c9fc4f814f76fbd6fe6b2bc/librad/src/net/protocol/cache.rs#L89-L92

and here https://github.com/radicle-dev/radicle-link/blob/bfdc3ec0c7ba542f2c9fc4f814f76fbd6fe6b2bc/librad/src/net/protocol/cache.rs#L139-L142

**Comment by geigerzaehler** [comment]
> Dropping a `Peer` does not drop the protocol state.

Not sure about the exact mechanism but the daemon, if it is used correctly, does make an effort to properly shutdown the protocol.

**Comment by geigerzaehler** [comment]
Thanks for clarifying this. I guess this means that the daemon doesn’t shut down the protocol properly. Am I right in assuming that dropping the `Peer` and calling the function returned by `Bound::accept()` while completing the future shuts down everything? Or is there something missing from `radicle_daemon::peer::Peer::start()`?

**Comment by kim** [comment]
> Am I right in assuming that dropping the Peer and calling the function returned by Bound::accept() while completing the future shuts down everything? 

It _should_.

> Or is there something missing from radicle_daemon::peer::Peer::start()?

Hm, I see that this actually consumes `self` which is not `Clone`. So I’m not sure how we could end up with a “dangling” `Peer`. Is this used somehow differently in upstream?

**Comment by geigerzaehler** [comment]
> It _should_.

And it looks like it does on latest master. I’m able to reproduce the “Too many open files” error on a previous version of `radicle-proxy` but not anymore. Using `lsof` also confirmed that inotify was the issue.
