### ISSUE TITLE
Evaluate tracing

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#81]
# Problem

The `log` crate is alright for ad-hoc output of what a program is doing, but is a bit too _unstructured_ to observe behaviour of a long-running program. It is also the case that some events might be interesting on the application layer (e.g. `pull` progress, peer connection status, ...).

# Potential Solution

While distributed tracing is not exactly applicable to our use-case, the [tracing](https://crates.io/crates/tracing) crate offers nice features, such as setting a context, timing, and structured data. It also appears that by choosing an appropriate subscriber, an application can decide what events they're interested in, and what to do with them.

# Alternatives

A more elaborate solution would be to thread some type of channel through the library, onto which we publish a predefined set of structured-data events, and forego logging entirely (except perhaps at `trace` level).

**Comment by xla** [comment]
@kim Corrected the link.

Without looking further into it a event stream io structured data sounds like the safer way of integrating. What are the potential events on that channel? Just to get an idea.

**Comment by kim** [comment]
@xla Can you articulate why this would be a safer way? You would never be able to exhaustively pattern-match on the event type.



> What are the potential events on that channel?

`git` sideband data (note that this is just text), connection events for "background" activity, discovery, membership, ... lots of informative, yet only semi-structured stuff.

**Comment by FintanH** [comment]
From looking at the `tracing` library, I'm into it. Features look nice, the syntax is pretty lightweight, and the documentation is good. I :+1: it.

**Comment by xla** [comment]
> @xla Can you articulate why this would be a safer way? You would never be able to exhaustively pattern-match on the event type.

I'd assume that an interface intended to introspect the events of the machinery (the channel proposal) is a more forward compatible way of integration than an incidental one relying on tracing information. Then again the subscriber part might just be that. So it doesn't really matter how the wiring is done as long as the contract doesn't break for unrelated reasons (e.g: tracing is not hot fashion anymore).

> `git` sideband data (note that this is just text), connection events for "background" activity, discovery, membership, ... lots of informative, yet only semi-structured stuff.

The git data will likely positively inform the UX around replication status of thangs. Where the membership info might help in communicating network topology and healthiness. Very excited to have access to these to make that info visible in form or another.

**Comment by kim** [comment]
Just to be clear: what I’m talking about is how the API of this tracing thing works, not that it is called “tracing”.

 For every public API call in `librad`, there will obviously be a return type, and a structured error type (although possibly `#[non_exhaustive]`). The things I’m concerned about here are emitted while a function runs, or completely out-of-band. They will not be structured — we won’t be parsing sideband data and give you a typed % done or anything. What we _can_ do, however, is to add tags or k/v pairs with context information. 

I don’t think the distinction between instrumentation and log-structured information surfaced to the user (but **not** for the application layer to implement any control flow apart from routing it to the right place) is very clear here. I would thus prefer to only having to put _one_ macro at interesting places, and defer the routing to some higher level.

**Comment by FintanH** [comment]
What I'm seeing from this conversation is that:

1. `radicle-link` wants to convey useful information to upstream consumers, e.g. peer status, git progress, etc.
2. However, `radicle-link` does not want to provide structured types, but rather key-value pairs.
3. `radicle-upstream` wants some guarantee around that information's existence and it doesn't suddenly change, e.g. one of the keys change in the key-value pairs.

So it seems to me that `radicle-link` could add trace calls to convey useful information via key-value pairs and should try to follow protobuf et al. practices for making changes to them.

`radicle-upstream` can use something like a `Subscriber` (if we go with `tracing`) to filter and output the information to application users.

Does that summarise everything do you think?
