### ISSUE TITLE
Consider JSON-LD for metadata

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#9]
[JSON-LD](https://www.w3.org/TR/json-ld) is a w3c standard for describing "linked data" schemas, as endorsed by "semantic web" proponents. It is relied upon by [ActivityPub](https://www.w3.org/TR/activitypub) and [DID](https://www.w3.org/TR/did-core) among others.

Full JSON-LD processing is very complicated, and **not** being considered here. It would however be _nice_ to re-use some of the existing vocabularies (e.g. of [Activity Streams](https://www.w3.org/TR/activitystreams-vocabulary)) in JSON-LD syntax, as it could open up some interop opportunities. Note that his applies mostly to more generic metadata, such as user profiles.

**Comment by FintanH** [comment]
Sounds like a pretty cool idea! I've encountered JSON-LD before during a info theory course. Don't know much about ActivityPub, DID, or Activity Streams, so I'll have to look into them :)

**Comment by kim** [comment]
The challenge is really to find appropriate vocabularies. In theory, JSON-LD is extensible / composable, but in practice that means that a _proper_ JSON-LD processor would need to retrieve the `@context` definitions from the internet (unless inlined). I'm thinking that a good approach might be to pick some well-known vocabularies (e.g. from ActivityPub) where we see potential for interop, and perhaps extend those with things we're missing (but not combine multiple external vocabularies).

**Comment by garbados** [comment]
Chiming in to +1 ActivityPub / ActivityStreams for user profiles, as it would simplify interoperability with the Fediverse -- a social network of more than a million users.
