### ISSUE TITLE
Expose stateful datatype like in mesh example

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#92]
All the wiring, options, callbacks

**Comment by FintanH** [comment]
I'd find it helpful if you pointed to out the code in the mesh example. As it stands I'm not quite sure what you mean by stateful datatype :)

**Comment by kim** [comment]
Basically some kind of "App Monad", based on the [MiniPeer](https://github.com/radicle-dev/radicle-link/blob/master/librad/examples/mesh.rs#L57), along with the [LocalStorage](https://github.com/radicle-dev/radicle-link/blob/master/librad/examples/mesh.rs#L85) impl. And then a digestable way to package all the bootstrapping boilerplate.
