### ISSUE TITLE
Implement real resolvers for entities and their histories.

### ISSUE THREAD

**Issue by massimiliano-mantione** [radicle-dev/radicle-link#95]
Implement a resolver that given an entity URN loads its revisions from locally stored git branches (those branches should belong to repositories tracked by or otherwise present on the local radicle device).

**Comment by FintanH** [comment]
> repositories tracked by or otherwise present on the local radicle device

These two should be the same — if I'm not mistaken? I say this because in our manifesto our first tenet is that we're offline first.

**Comment by kim** [comment]
Pending #127

**Comment by xla** [comment]
Is this issue still relevant?

**Comment by kim** [comment]
This is a function as per #259, #310
